# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Falafel
owner: Jett Robin Andres
email: jettrobin.andres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my technical blog! I will be posting my lifetime learnings
  here as a programmer and mobile app developer enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title
github_username:  jettandres
linkedin_username: jettrobinandres
facebook_username: jettrobin.andres

# Build settings
markdown: kramdown
